Updated ToS
griptape-ai/griptape-docs pull request #213
Opened 2024-02-14 20:32 UTC by cjkindel

Added instructions for generating from .docx with Pandoc

----
📚 Documentation preview 📚: https://griptape--213.org.readthedocs.build//213/

2024-02-14 23:31 UTC, derekpai requested changes
Some auto-markdown typos. Otherwise fine.

2024-02-14 23:31 UTC, derekpai commented on docs/griptape-cloud/terms-of-service.md
> +**BY CLICKING** "**I ACCEPT,**"**ACCESSING OUR USING GRIPTAPE INC'S
Need a space between the closed quote \" after 'accept' and 'accessing'

2024-02-14 23:31 UTC, derekpai commented on docs/griptape-cloud/terms-of-service.md
> +("GRIPTAPE"OR "WE" SERVICE**, YOU ("CUSTOMER"OR "YOU" AGREE THAT YOU
Need a space between the closed quote \" after 'customer' and 'or'

2024-02-14 23:31 UTC, derekpai commented on docs/griptape-cloud/terms-of-service.md
> +    Credentials**" to access and use the Service. Customer will provide,
Caught my own typo, this parenthetical string is not needed at all. Can cut parentheses and all chars between them.

2024-02-14 23:31 UTC, derekpai commented on docs/griptape-cloud/terms-of-service.md
> +        Customer.** **
I think there's a stray \** bold markdown here.

2024-02-14 23:31 UTC, derekpai commented on docs/griptape-cloud/terms-of-service.md
> +    2.  **Customer Data. **Customer hereby grants to Griptape a
Bold markdown closure \** is out of place, should be right after 'Data' before period?

2024-02-14 23:31 UTC, derekpai commented on docs/griptape-cloud/terms-of-service.md
> +        and enhancing the Griptape IPR.** **Customer owns and retains
Another stray bold markdown? \**

2024-02-14 23:31 UTC, derekpai commented on docs/griptape-cloud/terms-of-service.md
> +        Data). For purposes of this Agreement, "**Customer Data**"means
Need space after closed quote \" and 'means'

2024-02-14 23:31 UTC, derekpai commented on docs/griptape-cloud/terms-of-service.md
> +        this Agreement, "**Analytics**"means the data and information
Needs space between closed quote \" and 'means'

2024-02-14 23:31 UTC, derekpai commented on docs/griptape-cloud/terms-of-service.md
> +    Party Products**"means certain third-party applications, systems,
Needs space between closed quote \" and 'means'

2024-02-15 16:52 UTC, collindutter commented
I will fix the issue causing the build to fail

2024-02-15 19:06 UTC, collindutter approved these changes

2024-02-15 21:46 UTC, derekpai approved these changes
Looks good.

2024-02-15 21:49 UTC, derekpai commented
Non-blocking question: In the Poor (not Rich) view, does it mean anything that the text in latter sections change color from white to blue after the first row? I don't think this affects anything, but odd.

2024-02-15 22:47 UTC, merged